// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin from "./routes/admin.tsx";
import * as $api_path_ from "./routes/api/[...path].ts";
import * as $api_auth from "./routes/api/auth.ts";
import * as $exams_category_ from "./routes/exams/[category].tsx";
import * as $history from "./routes/history.tsx";
import * as $index from "./routes/index.tsx";
import * as $QuestionPalette from "./islands/QuestionPalette.tsx";
import * as $QuizEngine from "./islands/QuizEngine.tsx";
import * as $Timer from "./islands/Timer.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin.tsx": $admin,
    "./routes/api/[...path].ts": $api_path_,
    "./routes/api/auth.ts": $api_auth,
    "./routes/exams/[category].tsx": $exams_category_,
    "./routes/history.tsx": $history,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/QuestionPalette.tsx": $QuestionPalette,
    "./islands/QuizEngine.tsx": $QuizEngine,
    "./islands/Timer.tsx": $Timer,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
