interface Q { category: string; subject: string; text: string; options: string[]; correctIndex: number; explanation?: string; difficulty?: string; }
const C = "BANKING";
export const bankingQuestions: Q[] = [
// === QUANTITATIVE APTITUDE (50) ===
{category:C,subject:"quantitative_aptitude",text:"What is 15% of 240?",options:["32","36","40","34"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"If a man buys an article for ₹800 and sells it for ₹920, what is his profit percentage?",options:["12%","15%","18%","20%"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"The ratio of two numbers is 3:5. If their sum is 64, find the smaller number.",options:["20","24","28","30"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"A train 150m long passes a pole in 15 seconds. What is its speed in km/h?",options:["32","36","40","45"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"Simple interest on ₹5000 at 8% per annum for 3 years is:",options:["₹1000","₹1200","₹1400","₹1600"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"The average of 5 consecutive odd numbers is 21. What is the largest number?",options:["23","25","27","29"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"If x + y = 15 and xy = 56, find x² + y².",options:["97","113","109","121"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"A cistern can be filled in 8 hours and emptied in 12 hours. How long to fill when both pipes are open?",options:["20 hrs","24 hrs","18 hrs","16 hrs"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"What is the compound interest on ₹10000 at 10% for 2 years?",options:["₹2000","₹2100","₹2200","₹2500"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The LCM of 12, 18 and 24 is:",options:["48","72","96","108"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"A shopkeeper allows 10% discount and still gains 8%. His markup % is:",options:["15%","20%","18%","25%"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"quantitative_aptitude",text:"In how many ways can 5 people be seated in a row?",options:["60","120","24","720"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"A boat goes 12 km upstream in 3 hours and 16 km downstream in 2 hours. Speed of stream is:",options:["1 km/h","2 km/h","3 km/h","4 km/h"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"If the circumference of a circle is 44 cm, its area is:",options:["144 cm²","154 cm²","164 cm²","174 cm²"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The sum of first 20 natural numbers is:",options:["190","210","230","250"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"A can do a work in 10 days, B in 15 days. Together they finish in:",options:["5 days","6 days","7 days","8 days"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"What is the square root of 1764?",options:["38","42","44","46"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The cost price of 20 articles is equal to selling price of 16 articles. Profit % is:",options:["20%","25%","30%","15%"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"A mixture of 40 litres has milk and water in ratio 3:1. How much water to make ratio 2:1?",options:["5 litres","6 litres","8 litres","10 litres"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"quantitative_aptitude",text:"The average age of a class of 30 students is 14 years. If the teacher is included, average becomes 15. Teacher's age is:",options:["40","44","45","50"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"If a number is increased by 20% and then decreased by 20%, the net change is:",options:["+4%","-4%","0%","-2%"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The HCF of 36, 48 and 60 is:",options:["6","12","18","24"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"Two pipes fill a tank in 20 min and 30 min. Time to fill together:",options:["10 min","12 min","15 min","25 min"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"A sum doubles in 5 years at simple interest. The rate is:",options:["15%","20%","25%","10%"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The diagonal of a rectangle with sides 6cm and 8cm is:",options:["9 cm","10 cm","11 cm","12 cm"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"If 3x - 7 = 11, then x =",options:["4","5","6","7"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"The third proportional to 4 and 12 is:",options:["24","36","48","16"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"A car covers 450 km in 5 hours. Its speed in m/s is:",options:["20","25","30","35"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The volume of a cube with side 7 cm is:",options:["243 cm³","343 cm³","512 cm³","729 cm³"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"A man's age is 3 times his son's. After 10 years, he will be twice as old. Son's present age?",options:["8","10","12","15"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"What comes next: 2, 6, 12, 20, 30, ?",options:["40","42","44","46"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"If selling price is ₹450 and loss is 10%, cost price is:",options:["₹480","₹500","₹520","₹540"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The perimeter of a square with area 144 cm² is:",options:["44 cm","48 cm","52 cm","56 cm"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"12 men complete work in 18 days. How many men needed for 9 days?",options:["18","24","30","36"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The probability of getting a sum of 7 with two dice is:",options:["1/9","1/6","5/36","7/36"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"quantitative_aptitude",text:"Difference between CI and SI on ₹8000 for 2 years at 5% is:",options:["₹15","₹20","₹25","₹30"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"quantitative_aptitude",text:"The supplement of 65° is:",options:["105°","115°","125°","135°"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"A number when divided by 6 leaves remainder 3. What remainder when divided by 3?",options:["0","1","2","3"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"Speed ratio of A and B is 3:4. If A takes 20 min more, time taken by B is:",options:["40 min","50 min","60 min","80 min"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"quantitative_aptitude",text:"The value of √(0.0081) is:",options:["0.009","0.09","0.9","0.081"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"Average of first 10 prime numbers is:",options:["10.9","12.9","14.9","16.9"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"A tank is 3/5 full. If 16 litres is added, it becomes 4/5 full. Capacity of tank:",options:["60 L","70 L","80 L","90 L"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The product of two numbers is 120. Their sum is 23. The numbers are:",options:["8,15","10,12","9,14","11,12"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"100 oranges bought at ₹350 and sold at ₹48 per dozen. Profit/Loss %:",options:["12% profit","14.29% profit","15% profit","10% loss"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"quantitative_aptitude",text:"Time taken by ₹7000 to become ₹7350 at 10% SI is:",options:["4 months","5 months","6 months","8 months"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The angle between the hands of a clock at 3:30 is:",options:["60°","75°","80°","90°"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"How many numbers between 1 and 100 are divisible by both 3 and 5?",options:["5","6","7","8"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"In a class, 60% students pass Hindi, 70% pass English. If 40% pass both, what % fail both?",options:["5%","10%","15%","20%"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"quantitative_aptitude",text:"Three coins are tossed. Probability of at least one head:",options:["5/8","7/8","3/4","1/2"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The area of a triangle with sides 3, 4 and 5 cm is:",options:["5 cm²","6 cm²","7 cm²","8 cm²"],correctIndex:1,difficulty:"EASY"},

// === REASONING (50) ===
{category:C,subject:"reasoning",text:"Find the odd one out: 2, 5, 10, 17, 28, 37",options:["10","17","28","37"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"If COMPUTER is coded as DPNQVUFS, how is LAPTOP coded?",options:["MBQUPQ","NCRVQR","KDOSNO","MBQUPR"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"A is brother of B. B is sister of C. C is father of D. How is A related to D?",options:["Uncle","Father","Grandfather","Brother"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Complete the series: 3, 9, 27, 81, ?",options:["162","243","324","729"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"If in a code language FISH is written as EHRG, how is CRAB written?",options:["BQZZ","DSCB","BQZA","DSBC"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Pointing to a photograph, a man said 'She is the daughter of my grandfather's only son.' How is she related to him?",options:["Sister","Cousin","Mother","Aunt"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Find missing: 1, 4, 9, 16, 25, ?",options:["30","36","42","49"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"BDCE : FHGI :: JLMK : ?",options:["NPQO","NPOQ","NOQP","NQPO"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"If + means ×, × means ÷, ÷ means −, − means +, then 8 + 6 − 4 ÷ 2 × 2 =",options:["49","50","51","52"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Arrange: 1.Key 2.Lock 3.Door 4.Room 5.Furniture",options:["1,2,3,4,5","5,4,3,2,1","1,2,3,5,4","2,1,3,4,5"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"In a row of 30 children, Sita is 12th from left. Her position from right is:",options:["17th","18th","19th","20th"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"How many triangles are in a figure made of a square with both diagonals?",options:["4","6","8","10"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Calendar: If Jan 1 is Monday, what day is March 1 of the same non-leap year?",options:["Monday","Tuesday","Wednesday","Thursday"],correctIndex:3,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Which word CANNOT be formed from INTERNATIONAL?",options:["NATION","RATIONAL","REACTION","INTERNAL"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Mirror image: What is the mirror image of AMBULANCE?",options:["ECNALUBMA","ƎƆNA⅃UBMA","ƎƆN∀˥∩qW∀","Reverse text"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Odd one out: Apple, Mango, Potato, Orange",options:["Apple","Mango","Potato","Orange"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Statement: All cats are dogs. All dogs are birds. Conclusion: All cats are birds.",options:["Follows","Does not follow","Uncertain","Partially follows"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"A walks 5 km North, turns right walks 3 km, turns right walks 5 km. Distance from start?",options:["3 km","5 km","8 km","13 km"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Find the odd pair: AC, BD, CE, DF",options:["AC","BD","CE","DF"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"If FRIEND is coded as 69, ENEMY is coded as:",options:["55","58","65","62"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Complete: AZ, BY, CX, DW, ?",options:["EV","EU","FV","EW"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"A clock shows 3:15. What is the angle between hour and minute hands?",options:["0°","7.5°","15°","22.5°"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"6 people sit in a circle. How many ways can they be arranged?",options:["60","120","240","720"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Find the wrong number: 1, 2, 6, 24, 96, 720",options:["6","24","96","720"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Water image: what is the water image of the digit 5?",options:["5","2","ꟻ","Reversed 5"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"If ROSE = 6821, CHAIR = 73456 then SEARCH = ?",options:["124673","214673","216473","214637"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Cause: The government announced a new education policy. Effect:",options:["Schools will remain closed","Curriculum may be revised","Price of books decreased","Teachers went on strike"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Which figure completes the pattern? (Square, Circle, Triangle, Square, Circle, ?)",options:["Square","Circle","Triangle","Pentagon"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Ravi is taller than Sham. Mohan is taller than Ravi. Sham is taller than Kiran. Who is the shortest?",options:["Ravi","Sham","Mohan","Kiran"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Statement: Some books are pens. All pens are roads. Conclusion: Some books are roads.",options:["Follows","Does not follow","Both follow","Neither follows"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"How many times do 5 o'clock and 5:30 appear together on a clock in 24 hours?",options:["1","2","3","4"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"If South-East becomes North, what does North-West become?",options:["South","East","West","North-East"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Complete: Z1A, X2C, V3E, T4G, ?",options:["R5I","S5H","R5H","S4I"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Odd one out: January, March, May, June, July",options:["January","March","June","July"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"If '÷' means '+', '+' means '×', what is 12 ÷ 8 + 4?",options:["28","44","52","24"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Two statements: I. All pens are chairs. II. All chairs are tables. Conclusion: All pens are tables.",options:["Follows from I only","Follows from II only","Follows from both","Does not follow"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"B is east of A. C is north of B. D is west of C and north of A. Which is furthest north?",options:["A","B","C","D"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"A is 2 years older than B. B is 3 years older than C. If C is 15, what is A's age?",options:["18","19","20","21"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"What number replaces ? in: 4, 7, 12, 19, 28, ?",options:["37","38","39","40"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"In a code GREAT = 12345, AGREE = ?",options:["41234","41235","41223","41253"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Choose the Venn diagram: Dogs, Animals, Cats",options:["Two circles inside a bigger one","Three separate circles","Two overlapping circles in a big one","Three overlapping circles"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Count the cubes in a 3×3×3 arrangement:","options":["9","18","27","36"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"If + means brother, − means sister, × means father, ÷ means mother. What is A × B − C?",options:["C is A's sister","C is granddaughter","C is daughter of A's brother","C is A's niece"],correctIndex:3,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Find next: J, F, M, A, M, J, J, ?",options:["A","S","O","N"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Odd: 121, 144, 169, __(196)__, __(225)__. Which doesn't belong: 121, __(148)__, 169, 196?",options:["121","148","169","196"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"If Day after tomorrow is Saturday, what day was day before yesterday?",options:["Monday","Tuesday","Wednesday","Thursday"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"How many squares are in a 4×4 grid?",options:["16","20","25","30"],correctIndex:3,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"CAMEL : XZNVO :: HORSE : ?",options:["SLIHV","SLIHW","SLJHV","SLHIV"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"In a queue, Ram is 5th from front and 6th from back. How many people total?",options:["9","10","11","12"],correctIndex:1,difficulty:"EASY"},

// === ENGLISH (50) ===
{category:C,subject:"english",text:"Choose the correct spelling:",options:["Accomodation","Accommodation","Acommodation","Acomodation"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Synonym of 'Benevolent':",options:["Cruel","Kind","Strict","Angry"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Antonym of 'Transparent':",options:["Clear","Opaque","Visible","Obvious"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Fill in the blank: He has been working here ___ 2015.",options:["from","for","since","to"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"english",text:"The idiom 'Break the ice' means:",options:["To break something","To start a conversation","To freeze water","To be cold"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Choose correct voice: 'The letter was posted by her.'",options:["She post the letter","She posted the letter","She has posed the letter","She posting the letter"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"One word for 'A person who walks in sleep':",options:["Egoist","Somnambulist","Fatalist","Plagiarist"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"english",text:"Choose the correctly punctuated sentence:",options:["Its a beautiful day.","Its' a beautiful day.","It's a beautiful day.","Its a beautiful day"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"english",text:"Spot the error: 'Each of the students have completed their assignment.'",options:["Each of","the students","have completed","their assignment"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"The plural of 'analysis' is:",options:["Analysises","Analyses","Analysies","Analysi"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Synonym of 'Arduous':",options:["Easy","Difficult","Soft","Quick"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Antonym of 'Mundane':",options:["Ordinary","Exotic","Common","Regular"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Choose correct preposition: She is good ___ mathematics.",options:["in","at","on","for"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"'To burn the midnight oil' means:",options:["To waste oil","To study late at night","To cook at night","To set fire"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Choose the correct sentence:",options:["He don't know nothing","He doesn't know anything","He don't know anything","He doesn't know nothing"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Direct to Indirect: He said, 'I am happy.'",options:["He said that he is happy","He said that he was happy","He said that I am happy","He says that he was happy"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"A person who hates mankind is called:",options:["Philanthropist","Misanthrope","Misogynist","Altruist"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"english",text:"Fill in: Neither the students nor the teacher ___ present.",options:["were","was","are","have been"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Choose the word with correct spelling:",options:["Occurence","Occurance","Occurrence","Occurrance"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Synonym of 'Eloquent':",options:["Silent","Articulate","Dumb","Shy"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Meaning of 'A bolt from the blue':",options:["Thunder","A pleasant surprise","A sudden shock","Lightning"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Choose correct tense: 'She ___ here since morning.'",options:["is waiting","was waiting","has been waiting","had waited"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Antonym of 'Gregarious':",options:["Sociable","Solitary","Friendly","Outgoing"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"english",text:"Active voice of 'A song was sung by her':",options:["She sings a song","She sang a song","She was singing a song","She has sung a song"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"One word: Government by the people:",options:["Autocracy","Democracy","Monarchy","Theocracy"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Choose correct article: ___ honest man is respected.",options:["A","An","The","No article"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"'To cry over spilt milk' means:",options:["To waste milk","To regret past mistakes","To be sad","To cry loudly"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Fill in: I wish I ___ a bird.",options:["am","was","were","be"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"The collective noun for 'birds' is:",options:["Pack","Flock","Herd","Swarm"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Spot the error: 'The news are very shocking.'",options:["The","news","are","shocking"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Synonym of 'Obsolete':",options:["Modern","Outdated","Current","New"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Choose the correctly spelt word:",options:["Beautyful","Beautiful","Beautifull","Beutiful"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Meaning of 'To turn over a new leaf':",options:["To read a book","To change for the better","To flip a page","To garden"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Antonym of 'Proliferate':",options:["Increase","Decrease","Multiply","Grow"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"english",text:"Fill in: He insisted ___ my going there.",options:["on","in","for","at"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"The word 'ambiguous' means:",options:["Clear","Uncertain","Definite","Simple"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"'To hit below the belt' means:",options:["To punch someone","To act unfairly","To miss a target","To wear a belt"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Choose correct form: If I ___ you, I would study harder.",options:["am","was","were","be"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"One who cannot read or write is called:",options:["Scholar","Illiterate","Educated","Literate"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Which sentence is grammatically correct?",options:["Me and him went","Him and I went","He and I went","I and he went"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Synonym of 'Meticulous':",options:["Careless","Thorough","Quick","Lazy"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"english",text:"'Once in a blue moon' means:",options:["Every night","Very rarely","During full moon","Monthly"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Choose correct: 'The committee ___ divided in their opinion.'",options:["is","was","were","are"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"english",text:"Antonym of 'Affluent':",options:["Rich","Poor","Wealthy","Prosperous"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"'White elephant' means:",options:["An albino elephant","A costly but useless possession","A rare animal","A gift"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"The past participle of 'swim' is:",options:["Swam","Swimmed","Swum","Swimming"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"english",text:"Correctly spelt:",options:["Seperate","Separate","Saperate","Seperete"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Fill: We look ___ to the holidays.",options:["forward","for","up","after"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"english",text:"One word: A person who lives alone and avoids others:",options:["Extrovert","Recluse","Celebrity","Socialite"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Identify the figure of speech: 'The wind howled in the night.'",options:["Simile","Metaphor","Personification","Hyperbole"],correctIndex:2,difficulty:"MEDIUM"},

// === GENERAL AWARENESS (50) ===
{category:C,subject:"general_awareness",text:"RBI was established in which year?",options:["1930","1935","1940","1945"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Who is known as the Father of Indian Banking?",options:["RBI Governor","Raghuram Rajan","Sir Osborne Smith","None of these"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"NEFT stands for:",options:["National Electronic Funds Transfer","National Easy Fund Transfer","New Electronic Fund Transfer","None"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"What is the minimum age to open a savings account in India?",options:["10 years","12 years","18 years","No minimum"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"RTGS minimum amount for transfer is:",options:["₹1 lakh","₹2 lakh","No minimum","₹50,000"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"What is the full form of KYC?",options:["Know Your Customer","Keep Your Cash","King's Yearly Check","Know Your Currency"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"The headquarters of RBI is in:",options:["New Delhi","Kolkata","Mumbai","Chennai"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"SBI was nationalized in which year?",options:["1949","1955","1959","1969"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The regulator of the insurance sector in India is:",options:["RBI","SEBI","IRDAI","NABARD"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"What does SEBI stand for?",options:["Securities Exchange Board of India","Stock Exchange Bank of India","Securities and Exchange Board of India","None"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Who appoints the RBI Governor?",options:["Prime Minister","President","Finance Minister","Parliament"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Which bank is called the 'Banker's Bank'?",options:["SBI","NABARD","RBI","IDBI"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"IMPS stands for:",options:["Immediate Payment Service","Indian Money Payment System","Instant Money Payment Service","Immediate Money Payment System"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The tagline 'The World's Local Bank' belongs to:",options:["SBI","HSBC","Citibank","Standard Chartered"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"What is the full form of ATM?",options:["Automated Transaction Machine","Automatic Teller Machine","Automated Teller Machine","Auto Transfer Machine"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"NABARD was established in:",options:["1978","1980","1982","1984"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"How many banks were nationalized in 1969?",options:["6","10","14","20"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"What is Repo Rate?",options:["Rate at which RBI borrows from banks","Rate at which RBI lends to banks","Interest on savings","Fixed deposit rate"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"CRR stands for:",options:["Cash Reserve Ratio","Current Reserve Ratio","Credit Reserve Ratio","Central Reserve Ratio"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"NPA in banking stands for:",options:["Non-Performing Assets","National Performing Assets","Non-Productive Assets","None"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"The first bank established in India was:",options:["Bank of Hindustan","SBI","RBI","Bank of Calcutta"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"general_awareness",text:"IFSC code has how many characters?",options:["8","10","11","12"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Financial year in India starts from:",options:["January 1","March 1","April 1","July 1"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"What is the currency of Japan?",options:["Won","Yuan","Yen","Dollar"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Which organization provides deposit insurance in India?",options:["RBI","DICGC","SEBI","NABARD"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"general_awareness",text:"PAN card is issued by:",options:["RBI","Income Tax Department","Ministry of Finance","SEBI"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Fiscal Policy is related to:",options:["Money supply","Government revenue and expenditure","Interest rates","Exchange rates"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"GDP stands for:",options:["Gross Domestic Product","General Domestic Product","Gross Development Product","General Development Product"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Which is the largest public sector bank in India?",options:["Bank of Baroda","Punjab National Bank","SBI","Union Bank"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Mutual Funds are regulated by:",options:["RBI","SEBI","IRDAI","NABARD"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The monetary policy is decided by:",options:["Finance Ministry","SEBI","RBI","NITI Aayog"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"UPI was launched by:",options:["RBI","NPCI","SBI","Government of India"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"What is the maximum deposit insured by DICGC?",options:["₹1 lakh","₹2 lakh","₹5 lakh","₹10 lakh"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The Indian Rupee symbol ₹ was designed by:",options:["RBI","D. Udaya Kumar","Amartya Sen","Finance Ministry"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"What is SLR?",options:["Statutory Liquidity Ratio","Standard Lending Rate","Secured Lending Ratio","None"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Which committee recommended financial inclusion?",options:["Narasimham Committee","Rangarajan Committee","Kelkar Committee","Raghuram Rajan Committee"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"general_awareness",text:"Digital India initiative was launched in:",options:["2014","2015","2016","2017"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"GST was implemented on:",options:["April 1, 2017","July 1, 2017","January 1, 2018","April 1, 2018"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"What is the full form of SWIFT?",options:["Society for Worldwide Interbank Financial Telecommunication","Standard World International Fund Transfer","Secure World Interbank Fund Transfer","None"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Base Rate system was introduced by RBI in:",options:["2008","2010","2012","2015"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"general_awareness",text:"The concept of 'Small Finance Banks' was recommended by:",options:["Nachiket Mor Committee","Rangarajan Committee","Kelkar Committee","Usha Thorat Committee"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"general_awareness",text:"Jan Dhan Yojana was launched in:",options:["2013","2014","2015","2016"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Which is NOT a function of RBI?",options:["Issue currency","Regulate banks","Collect income tax","Manage forex reserves"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"What is the reverse repo rate?",options:["Rate for bank loans","Rate at which RBI borrows from banks","Rate for home loans","None"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"CRISIL is a:",options:["Bank","Credit rating agency","Insurance company","Mutual fund"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"MUDRA Bank was launched to help:",options:["Large corporations","Micro and small enterprises","Foreign companies","Government bodies"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The first Indian bank to get ISO certification was:",options:["SBI","Canara Bank","ICICI","HDFC"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"general_awareness",text:"What does MSME stand for?",options:["Micro Small Medium Enterprise","Micro Small and Medium Enterprises","Ministry of Small and Medium Enterprises","None"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"India's first payment bank is:",options:["Airtel Payments Bank","Paytm Payments Bank","India Post","Jio Payments"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The Banking Ombudsman Scheme was introduced in:",options:["1990","1995","2000","2006"],correctIndex:1,difficulty:"HARD"},

// === COMPUTER KNOWLEDGE (50) ===
{category:C,subject:"computer_knowledge",text:"CPU stands for:",options:["Central Processing Unit","Computer Personal Unit","Central Program Utility","Computer Processing Unit"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"Which is NOT an input device?",options:["Keyboard","Mouse","Monitor","Scanner"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"RAM stands for:",options:["Read Access Memory","Random Access Memory","Random Available Memory","Read All Memory"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"Which key is used to delete a character to the left of cursor?",options:["Delete","Backspace","Enter","Spacebar"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"The brain of a computer is:",options:["RAM","Hard Disk","CPU","Monitor"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"HTTP stands for:",options:["Hyper Text Transfer Protocol","High Text Transfer Protocol","Hyper Transfer Text Protocol","None"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"Which of these is an operating system?",options:["MS Word","Google Chrome","Linux","Photoshop"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"1 KB equals:",options:["1000 bytes","1024 bytes","1048 bytes","512 bytes"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"Which language is directly understood by computer?",options:["C++","Java","Machine Language","Python"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"The shortcut Ctrl+C is used to:",options:["Cut","Copy","Close","Create"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"Which is a volatile memory?",options:["ROM","Hard Disk","RAM","CD-ROM"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"URL stands for:",options:["Universal Resource Locator","Uniform Resource Locator","Universal Record Locator","Uniform Record Locator"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"Which device converts digital signals to analog?",options:["Router","Modem","Hub","Switch"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"The extension of a Word document is:",options:[".xls",".ppt",".docx",".txt"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"What is a Firewall?",options:["A wall to prevent fire","Network security system","A browser","An antivirus"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"Which is NOT a web browser?",options:["Chrome","Firefox","Outlook","Safari"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"BIOS stands for:",options:["Basic Input Output System","Binary Input Output System","Basic Integrated Operating System","None"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"Which topology connects all devices to a central hub?",options:["Bus","Ring","Star","Mesh"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"The shortcut Ctrl+Z is used for:",options:["Zoom","Undo","Close","Copy"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"SQL stands for:",options:["Structured Query Language","Standard Query Language","System Query Language","None"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"Which protocol is used for sending emails?",options:["FTP","HTTP","SMTP","TCP"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"A byte consists of:",options:["4 bits","8 bits","16 bits","32 bits"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"The first computer virus was called:",options:["ILOVEYOU","Creeper","Morris","Mydoom"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"computer_knowledge",text:"Which generation of computers used transistors?",options:["First","Second","Third","Fourth"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"LAN stands for:",options:["Large Area Network","Local Area Network","Long Area Network","Local Access Network"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"Which key combination selects all text?",options:["Ctrl+A","Ctrl+S","Ctrl+E","Ctrl+X"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"What is phishing?",options:["Fishing online","A cyberattack to steal data","A programming language","A search engine"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"Binary number system uses:",options:["0-9","0 and 1","0-7","0-F"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"DBMS stands for:",options:["Data Base Management System","Database Management Software","Digital Base Management System","None"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"Which of the following is a search engine?",options:["Facebook","Google","WhatsApp","Instagram"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"The main circuit board of a computer is called:",options:["Graphics card","Motherboard","Hard drive","Processor"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"Which is an example of system software?",options:["MS Excel","Photoshop","Windows","Chrome"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"IP stands for:",options:["Internet Protocol","Internet Program","Internal Protocol","Intranet Protocol"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"Cache memory is used to:",options:["Store permanent data","Speed up CPU processing","Connect to internet","Store backups"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"What does USB stand for?",options:["Universal Serial Bus","United System Bus","Universal System Backup","None"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"Which MS Office tool is used for presentations?",options:["Word","Excel","PowerPoint","Access"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"What is cloud computing?",options:["Computing in clouds","Using remote servers over internet","A type of hardware","Weather computing"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"Which key is used to refresh a web page?",options:["F1","F3","F5","F7"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"PDF stands for:",options:["Portable Document Format","Personal Document File","Printed Document Format","None"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"Which of these is a programming language?",options:["HTML","Python","Photoshop","Windows"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"What is malware?",options:["A type of hardware","Malicious software","An email","A browser"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"The output quality of a printer is measured in:",options:["Hertz","Megabytes","DPI","Watts"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"Which company developed the Windows operating system?",options:["Apple","Google","Microsoft","IBM"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"OCR stands for:",options:["Optical Character Recognition","Online Character Reader","Optical Code Reader","None"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"VPN stands for:",options:["Virtual Private Network","Virtual Public Network","Verified Private Network","None"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"Which is NOT a type of computer?",options:["Mainframe","Supercomputer","Mega computer","Microcomputer"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"ALU stands for:",options:["Arithmetic Logic Unit","Advanced Logic Unit","Array Logic Unit","None"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"computer_knowledge",text:"Which shortcut saves a document?",options:["Ctrl+P","Ctrl+S","Ctrl+D","Ctrl+N"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"computer_knowledge",text:"IPv4 address is how many bits?",options:["16","32","64","128"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"computer_knowledge",text:"An example of non-volatile memory is:",options:["RAM","Cache","ROM","Register"],correctIndex:2,difficulty:"MEDIUM"},
];
