interface Q { category: string; subject: string; text: string; options: string[]; correctIndex: number; explanation?: string; difficulty?: string; }
const C = "DEFENCE";
export const defenceQuestions: Q[] = [
// === MATHEMATICS (50) ===
{category:C,subject:"mathematics",text:"The value of 999 × 999 is:",options:["998001","997001","999001","996001"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"If 3ˣ = 243, then x =",options:["3","4","5","6"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"The area of a rhombus with diagonals 10 and 12 cm:",options:["50 cm²","55 cm²","60 cm²","65 cm²"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"20% of a number is 50. The number is:",options:["200","250","300","350"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"The value of cos 0° is:",options:["0","1","-1","1/2"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"If the perimeter of a square is 64 cm, its area is:",options:["144 cm²","196 cm²","256 cm²","324 cm²"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"Three numbers in AP with sum 15 and product 80. Middle number:",options:["3","4","5","6"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"How many 3-digit numbers are divisible by 7?",options:["126","128","130","132"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"The complement of 35° is:",options:["45°","55°","65°","145°"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"A sum becomes ₹6050 in 2 years at 10% CI. The sum is:",options:["₹4000","₹4500","₹5000","₹5500"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The distance between points (3,4) and (0,0) is:",options:["4","5","6","7"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"Two numbers ratio 3:5. Sum is 96. Difference:",options:["18","20","24","30"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"Curved surface area of cone with r=7, l=25:",options:["440 cm²","500 cm²","550 cm²","600 cm²"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"5 men = 8 women in work. 2 men + 3 women do it in how many days if 4 men finish in 12 days?",options:["10","12","14","16"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"LCM of 15, 20, 30 is:",options:["30","60","120","180"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"The slope of line 2x + 3y = 6 is:",options:["2/3","-2/3","3/2","-3/2"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"A clock strikes 12 in 33 seconds. Time for 6 strikes:",options:["15 sec","16.5 sec","16 sec","18 sec"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"The number of faces of a tetrahedron:",options:["3","4","5","6"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"If a cylinder has r=3 and h=7, its volume is:",options:["63π","54π","45π","72π"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"Two trains 100m each, speed 50 km/h each in opposite direction. Crossing time:",options:["6.2 sec","7.2 sec","8.2 sec","9.2 sec"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The value of sin²30° + cos²60° is:",options:["0","1/2","1","3/2"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"Profit % when CP=₹40 and SP=₹50:",options:["20%","25%","30%","35%"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"The area of a trapezium with parallel sides 8,12 and height 5:",options:["40","50","60","70"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"If x² - 5x + 6 = 0, then x =",options:["1,6","2,3","3,4","1,5"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"The 10th term of AP: 3, 7, 11, 15...",options:["35","37","39","41"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"9 workers finish in 15 days. To finish in 9 days:",options:["12","13","14","15"],correctIndex:3,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The value of (25)^(3/2) is:",options:["75","100","125","150"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"A right triangle with legs 5 and 12 has hypotenuse:",options:["11","12","13","14"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"Ratio of areas of two similar triangles with sides in ratio 2:3:",options:["2:3","4:9","8:27","1:3"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"Mean deviation of 2,4,6,8,10 from mean is:",options:["2","2.4","3","3.2"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"If ₹1000 amounts to ₹1331 in 3 years at CI, rate:",options:["8%","9%","10%","11%"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The centroid divides median in ratio:",options:["1:1","1:2","2:1","2:3"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The sum of first 5 terms of GP: 1,2,4,8...:",options:["15","16","31","32"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"A circle inscribed in a square of side 10. Area of circle:",options:["25π","50π","75π","100π"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The mode of 5,3,4,5,6,5,7,5,8 is:",options:["3","5","7","8"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"If log₁₀ 100 = x, then x =",options:["1","2","10","100"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"The number of zeros in one crore is:",options:["5","6","7","8"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"Two coins tossed. Probability of exactly one head:",options:["1/4","1/3","1/2","3/4"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"If tan A = 1, then A =",options:["30°","45°","60°","90°"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"The area of ring with inner radius 5 and outer 8:",options:["29π","39π","49π","59π"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"Average of 5 numbers is 20. One removed, average is 15. Removed number:",options:["30","35","40","45"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The reciprocal of 0.25 is:",options:["2","3","4","5"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"Discount % when MP=₹500, SP=₹400:",options:["15%","18%","20%","25%"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"A ladder resting against wall makes 60° with ground. Distance from wall if ladder is 10m:",options:["4m","5m","6m","7m"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The product of HCF and LCM of 12 and 18:",options:["36","108","216","324"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"Number of solutions of 2x+3y=12 in positive integers:",options:["1","2","3","4"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"sec²θ - tan²θ =",options:["0","1","sin²θ","cos²θ"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"The median of 2,8,3,6,4,7,5 is:",options:["4","5","6","7"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"Distance formula: dist between (1,2) and (4,6):",options:["3","4","5","6"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"If a+b=10 and ab=24, then a²+b² =",options:["48","52","56","60"],correctIndex:1,difficulty:"MEDIUM"},

// === GK (50) ===
{category:C,subject:"general_knowledge",text:"The motto of Indian Army is:",options:["Jai Hind","Service Before Self","Nischay Kar Apni Jeet Karo","Satyamev Jayate"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The Indian Air Force was established in:",options:["1932","1935","1947","1950"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"Indian Navy Day is celebrated on:",options:["Oct 8","Dec 4","Jan 15","Mar 1"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"The National Defence Academy is located at:",options:["Dehradun","Pune","Khadakwasla","Chennai"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"Who is the Supreme Commander of Indian Armed Forces?",options:["Prime Minister","Defence Minister","President","Army Chief"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The Param Vir Chakra is awarded for:",options:["Bravery in sports","Most conspicuous bravery in war","Scientific achievement","Social service"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"Kargil War was fought in:",options:["1997","1998","1999","2000"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The rank of Field Marshal in Indian Army has been held by:",options:["1 person","2 people","3 people","4 people"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"general_knowledge",text:"Which is India's indigenous aircraft carrier?",options:["INS Vikrant","INS Vikramaditya","INS Viraat","INS Arihant"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"Rashtriya Indian Military College is in:",options:["Pune","Dehradun","Khadakwasla","Hyderabad"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"The first woman to join Indian Armed Forces as an officer was in:",options:["1990","1992","1993","1995"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"general_knowledge",text:"DRDO stands for:",options:["Defence Research and Design Organisation","Defence Research and Development Organisation","Defence Research Department Organisation","None"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The highest gallantry award in India is:",options:["Ashoka Chakra","Param Vir Chakra","Vir Chakra","Maha Vir Chakra"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"Indian Army Day is celebrated on:",options:["Jan 15","Jan 26","Aug 15","Oct 2"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The Battle of Longewala was fought during:",options:["1965 War","1971 War","Kargil War","1962 War"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"India's first nuclear test was conducted in:",options:["1971","1974","1998","2000"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"Operation Vijay was related to:",options:["1971 War","Kargil War","Sri Lanka","Kashmir"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"The Indian Military Academy is located at:",options:["Pune","Khadakwasla","Dehradun","Chennai"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"Agni missile is a:",options:["Surface-to-Air","Surface-to-Surface","Air-to-Air","Submarine-launched"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"The Siachen conflict is between India and:",options:["China","Bangladesh","Pakistan","Nepal"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"Which Indian state does not share an international border?",options:["Rajasthan","Madhya Pradesh","Assam","Punjab"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The capital of Russia is:",options:["St. Petersburg","Moscow","Kiev","Minsk"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The United Nations was founded in:",options:["1942","1944","1945","1948"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"Which country has the largest area?",options:["China","USA","Canada","Russia"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The currency of China is:",options:["Yen","Won","Yuan","Ringgit"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"Who was the first Indian in space?",options:["Kalpana Chawla","Rakesh Sharma","Sunita Williams","None"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The Bhagat Singh was executed in:",options:["1929","1930","1931","1932"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"The longest wall in the world is:",options:["Berlin Wall","Hadrian's Wall","Great Wall of China","None"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"Which river flows through Paris?",options:["Thames","Rhine","Seine","Danube"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The largest island in the world is:",options:["Borneo","Madagascar","Greenland","Sumatra"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"NATO was formed in:",options:["1945","1947","1949","1951"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"The Olympic Games are held every:",options:["2 years","3 years","4 years","5 years"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"Which organ purifies blood in the human body?",options:["Heart","Liver","Kidney","Lungs"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The full form of ISRO is:",options:["Indian Space Research Organisation","Indian Scientific Research Organisation","Indian Space Research Office","None"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"Which freedom fighter is known as 'Lokmanya'?",options:["Mahatma Gandhi","Bal Gangadhar Tilak","Gopal Krishna Gokhale","Subhash Chandra Bose"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"Mount Everest is in which country?",options:["India","China","Nepal","Tibet"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The Wright Brothers are famous for:",options:["Telephone","Airplane","Automobile","Radio"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The largest ocean current is:",options:["Gulf Stream","Antarctic Circumpolar","Kuroshio","North Atlantic"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"general_knowledge",text:"Vitamin A deficiency causes:",options:["Scurvy","Night blindness","Beriberi","Rickets"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"What is the national animal of India?",options:["Lion","Elephant","Tiger","Peacock"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The Suez Canal connects:",options:["Atlantic and Pacific","Red Sea and Mediterranean","Arabian Sea and Red Sea","Indian Ocean and Pacific"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"Chandrayaan-1 was launched in:",options:["2005","2006","2008","2010"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"Which gas is used in balloons for flying?",options:["Hydrogen","Oxygen","Helium","Nitrogen"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The first PM of independent India was:",options:["Mahatma Gandhi","Jawaharlal Nehru","Sardar Patel","BR Ambedkar"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The Indian Constitution has been amended how many times (approx)?",options:["50","75","105","125"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"general_knowledge",text:"Which state is known as 'Spice Garden of India'?",options:["Tamil Nadu","Karnataka","Kerala","Goa"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"The International Court of Justice is in:",options:["New York","Geneva","The Hague","Paris"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"What is the chemical formula of Ozone?",options:["O","O₂","O₃","O₄"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_knowledge",text:"The first Asian Games were held in:",options:["Tokyo","Manila","New Delhi","Jakarta"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_knowledge",text:"Who invented the telephone?",options:["Thomas Edison","Alexander Graham Bell","Guglielmo Marconi","Nikola Tesla"],correctIndex:1,difficulty:"EASY"},
];
