interface Q { category: string; subject: string; text: string; options: string[]; correctIndex: number; explanation?: string; difficulty?: string; }
const C = "RAILWAYS";
export const railwaysQuestions: Q[] = [
// === MATHEMATICS (50) ===
{category:C,subject:"mathematics",text:"What is 12.5% of 800?",options:["80","90","100","120"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"The average of first 50 natural numbers is:",options:["24.5","25","25.5","26"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"If x:y = 3:4, then (4x+5y):(5x+4y) is:",options:["31:32","32:31","30:31","31:30"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"A train 300m long passes a pole in 20 sec. Speed in km/h?",options:["48","54","60","72"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"A shopkeeper marks up by 40% and gives 20% discount. Profit %?",options:["8%","10%","12%","14%"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The HCF of 24, 36, 48 is:",options:["6","8","12","24"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"Simple interest for 2 years at 5% on ₹4000 is:",options:["₹300","₹400","₹500","₹600"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"Area of equilateral triangle with side 6 cm:",options:["9√3","12√3","15√3","18√3"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The value of 3⁴ is:",options:["12","27","64","81"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"Two trains of 120m and 80m at 40 and 50 km/h cross each other in:",options:["6 sec","7 sec","8 sec","9 sec"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"If A can do work in 15 days and B in 20 days, together:",options:["7.67 days","8.57 days","9 days","10 days"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The cube root of 1728 is:",options:["10","11","12","13"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"25% of 400 + 40% of 250 =",options:["190","200","210","220"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"In a triangle, angles are in ratio 1:2:3. The largest angle is:",options:["60°","80°","90°","120°"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"A car goes 100 km at 50 km/h and 100 km at 40 km/h. Average speed?",options:["44.4 km/h","45 km/h","46 km/h","47 km/h"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"The perimeter of a semicircle with diameter 14 cm:",options:["28 cm","36 cm","44 cm","50 cm"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"If ₹500 becomes ₹583.20 at CI in 2 years, rate is:",options:["6%","7%","8%","9%"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"The number of prime numbers between 1 and 50:",options:["12","14","15","16"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"Selling price ₹1260 with 5% profit. Cost price?",options:["₹1100","₹1150","₹1200","₹1250"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"The sum of angles of a quadrilateral is:",options:["180°","270°","360°","540°"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"If a pipe fills tank in 6 hrs and another empties in 8 hrs. Net filling time:",options:["12 hrs","18 hrs","24 hrs","30 hrs"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"15 workers finish in 12 days. How many workers for 10 days?",options:["15","16","18","20"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The value of tan 60° is:",options:["1","√3","1/√3","2"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"A dice is thrown. Probability of getting even number:",options:["1/6","1/3","1/2","2/3"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"Volume of cone with r=7, h=24:",options:["1232 cm³","616 cm³","1848 cm³","924 cm³"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"What comes next: 2,3,5,8,13,21,?",options:["26","31","34","42"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The angle subtended by diameter at circumference is:",options:["45°","60°","90°","180°"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"If sin A = 3/5, then cos A =",options:["3/5","4/5","5/4","5/3"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"A man buys 5 for ₹3 and sells 3 for ₹5. Profit %?",options:["100.67%","125.33%","138.89%","150%"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"Two supplementary angles. One is 40° more than other. Angles?",options:["50°,130°","60°,120°","70°,110°","80°,100°"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"The volume of a hemisphere with r=3 is:",options:["18π","36π","54π","72π"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"If 15% of x = 45, then x =",options:["200","250","300","350"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"Total surface area of a cube with side 5 cm:",options:["125 cm²","150 cm²","175 cm²","200 cm²"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"A boat's speed in still water is 10 km/h, stream 2 km/h. Downstream speed:",options:["8","10","12","14"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"The range of data set {3,7,2,9,5,1,8} is:",options:["6","7","8","9"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"If log 2 = 0.301, log 8 =",options:["0.602","0.903","1.204","2.408"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"A rectangular field 120m × 80m. Area in hectares:",options:["0.6","0.8","0.96","1.2"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"If the diagonal of a square is 10 cm, its area is:",options:["25 cm²","50 cm²","75 cm²","100 cm²"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"What is the unit digit of 7⁹⁵?",options:["1","3","7","9"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"LCM of 4, 6, 8 is:",options:["12","24","36","48"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"A invested ₹6000 and B ₹8000. Profit ₹7000. A's share:",options:["₹2500","₹3000","₹3500","₹4000"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The exterior angle of a regular hexagon is:",options:["40°","45°","60°","72°"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"Speed of a man who covers 600m in 5 minutes in km/h:",options:["6.5","7","7.2","8"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"(a²-b²) equals:",options:["(a-b)²","(a+b)(a-b)","a²+b²","2ab"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"Circumradius of equilateral triangle with side a:",options:["a/√3","a√3/3","a/√3","a√3"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"Marked price ₹500. Two successive discounts of 10% and 20%. Net price:",options:["₹340","₹350","₹360","₹380"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"mathematics",text:"The greatest 4-digit number divisible by 12, 15, 20 is:",options:["9900","9960","9980","9999"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"mathematics",text:"Number of edges in a cuboid:",options:["6","8","10","12"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"If 2ˣ = 64, then x =",options:["4","5","6","7"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"mathematics",text:"The mean of first 10 even numbers is:",options:["10","11","12","13"],correctIndex:1,difficulty:"EASY"},

// === GENERAL SCIENCE (50) ===
{category:C,subject:"general_science",text:"Which gas is most abundant in Earth's atmosphere?",options:["Oxygen","Nitrogen","Carbon Dioxide","Argon"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"The powerhouse of the cell is:",options:["Nucleus","Ribosome","Mitochondria","Golgi body"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Newton's first law is also called:",options:["Law of Action","Law of Inertia","Law of Momentum","Law of Gravity"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Which blood group is universal donor?",options:["A","B","AB","O"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Vitamin C deficiency causes:",options:["Rickets","Beriberi","Scurvy","Night blindness"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_science",text:"The chemical symbol for Gold is:",options:["Go","Gd","Au","Ag"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Sound travels fastest in:",options:["Air","Water","Vacuum","Solid"],correctIndex:3,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"Photosynthesis occurs in which organelle?",options:["Mitochondria","Chloroplast","Ribosome","Nucleus"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"The largest organ of human body is:",options:["Liver","Brain","Skin","Heart"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_science",text:"pH value of human blood is approximately:",options:["6.4","7.0","7.4","8.0"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"Which metal is liquid at room temperature?",options:["Iron","Mercury","Lead","Copper"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Number of chromosomes in humans:",options:["23","44","46","48"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Ohm's Law relates:",options:["Mass and velocity","Voltage, current and resistance","Force and acceleration","Pressure and volume"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"Deficiency of iron causes:",options:["Goitre","Anaemia","Rickets","Scurvy"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Which lens is used to correct myopia?",options:["Convex","Concave","Bifocal","Cylindrical"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"The hardest naturally occurring substance is:",options:["Iron","Platinum","Diamond","Quartz"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_science",text:"DNA stands for:",options:["Dioxyribo Nucleic Acid","Deoxyribo Nucleic Acid","Di Nucleic Acid","None"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Which planet has the most moons?",options:["Jupiter","Saturn","Uranus","Neptune"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"Rusting of iron is:",options:["Physical change","Chemical change","Both","Neither"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Normal body temperature is:",options:["36°C","37°C","38°C","39°C"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Which gas extinguishes fire?",options:["Oxygen","Hydrogen","Carbon Dioxide","Nitrogen"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Light year is a unit of:",options:["Time","Speed","Distance","Mass"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Which acid is found in lemon?",options:["Acetic acid","Citric acid","Lactic acid","Formic acid"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Red blood cells are produced in:",options:["Liver","Heart","Bone marrow","Kidney"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"The SI unit of electric current is:",options:["Volt","Ampere","Ohm","Watt"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Which vitamin helps in blood clotting?",options:["Vitamin A","Vitamin C","Vitamin D","Vitamin K"],correctIndex:3,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"Baking soda is chemically:",options:["NaCl","NaHCO₃","Na₂CO₃","CaCO₃"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"Which planet is known as Morning Star?",options:["Mars","Venus","Jupiter","Mercury"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Insulin is produced by which organ?",options:["Liver","Pancreas","Kidney","Thyroid"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"The speed of light is approximately:",options:["3×10⁶ m/s","3×10⁸ m/s","3×10¹⁰ m/s","3×10⁴ m/s"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"The process of conversion of solid to gas directly:",options:["Evaporation","Condensation","Sublimation","Deposition"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"Which part of the brain controls balance?",options:["Cerebrum","Cerebellum","Medulla","Pons"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"Bleaching powder formula is:",options:["CaCl₂","Ca(OCl)Cl","CaO","Ca(OH)₂"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"general_science",text:"Refraction of light causes:",options:["Change in speed","Change in wavelength","Bending of light","All of these"],correctIndex:3,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"The study of fungi is called:",options:["Mycology","Virology","Bacteriology","Botany"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"Which gas causes acid rain?",options:["Oxygen","Carbon monoxide","Sulphur dioxide","Nitrogen"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"The chemical formula of common salt is:",options:["KCl","NaCl","CaCl₂","MgCl₂"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Plant cells differ from animal cells by having:",options:["Nucleus","Mitochondria","Cell wall","Ribosome"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_science",text:"The boiling point of water at sea level is:",options:["90°C","95°C","100°C","110°C"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Which hormone controls blood sugar?",options:["Thyroxine","Insulin","Adrenaline","Estrogen"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_science",text:"An element with atomic number 8 is:",options:["Carbon","Nitrogen","Oxygen","Fluorine"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"The principle of rocket propulsion is based on:",options:["Newton's 1st law","Newton's 2nd law","Newton's 3rd law","Law of conservation of energy"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"Dengue fever is spread by:",options:["Anopheles mosquito","Aedes mosquito","Housefly","Cockroach"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"The lens of the human eye is:",options:["Convex","Concave","Flat","Cylindrical"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"CNG stands for:",options:["Compressed Natural Gas","Common Natural Gas","Converted Natural Gas","None"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Which metal is used in thermometers?",options:["Lead","Zinc","Mercury","Aluminum"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_science",text:"Antibodies are produced by:",options:["Red blood cells","White blood cells","Platelets","Plasma"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"The SI unit of pressure is:",options:["Newton","Pascal","Joule","Watt"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_science",text:"Which vitamin is also known as Ascorbic acid?",options:["Vitamin A","Vitamin B","Vitamin C","Vitamin D"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_science",text:"The process of respiration is:",options:["Endothermic","Exothermic","Neither","Both"],correctIndex:1,difficulty:"MEDIUM"},
];
