interface Q { category: string; subject: string; text: string; options: string[]; correctIndex: number; explanation?: string; difficulty?: string; }
const C = "SSC";
export const sscQuestions: Q[] = [
// === QUANTITATIVE APTITUDE (50) ===
{category:C,subject:"quantitative_aptitude",text:"What is the value of 25² - 24²?",options:["49","47","51","48"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"If the price is reduced by 25%, how much more must be bought for ₹100?",options:["20%","25%","33.33%","50%"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"Find 8% of 450.",options:["32","36","45","40"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"The average of 10, 20, 30, 40, 50 is:",options:["25","30","35","40"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"A man walks at 5 km/h for 6 hours and 4 km/h for 4 hours. Average speed?",options:["4.4 km/h","4.6 km/h","4.8 km/h","5 km/h"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The ratio 2:3 is same as:",options:["4:9","6:9","8:9","3:2"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"If a:b = 2:3 and b:c = 4:5, then a:b:c =",options:["8:12:15","2:3:5","4:6:5","8:12:10"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"What is the area of a circle with radius 14 cm?",options:["516 cm²","616 cm²","716 cm²","816 cm²"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The value of sin²45° + cos²45° is:",options:["0","1","2","1/2"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"If x = 3, then x³ + 3x² + 3x + 1 =",options:["27","64","125","8"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The greatest number which divides 43 and 91 leaving remainder 1:",options:["2","6","7","14"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The sum of interior angles of a hexagon is:",options:["540°","600°","720°","900°"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"If the selling price is double the cost price, profit % is:",options:["50%","100%","150%","200%"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"In a triangle, if two angles are 50° and 70°, the third is:",options:["50°","60°","70°","80°"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"Pipe A fills tank in 12 hours, Pipe B in 18 hours. Together:",options:["6.2 hrs","7.2 hrs","8.2 hrs","9 hrs"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The value of tan 45° is:",options:["0","1","√3","1/√3"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"A number is 4 times another. Sum is 60. The larger number:",options:["36","40","45","48"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"What is the curved surface area of a cylinder with r=7, h=10?",options:["440 cm²","400 cm²","420 cm²","460 cm²"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"Two numbers are in ratio 5:7. Difference is 12. Smaller number?",options:["28","30","32","35"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The value of (a+b)² when a=3, b=4:",options:["25","36","49","64"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"A train 200m long crosses a bridge 300m long in 50 seconds. Speed?",options:["30 km/h","36 km/h","40 km/h","45 km/h"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"What % is 15 of 75?",options:["15%","20%","25%","30%"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"Side of a cube with volume 512 cm³:",options:["6","7","8","9"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The median of 3,5,7,9,11 is:",options:["5","7","9","11"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"If 4 workers finish in 10 days, 5 workers finish in:",options:["7 days","8 days","9 days","12 days"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The smallest prime number is:",options:["0","1","2","3"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"If COS θ = 4/5, find SIN θ:",options:["3/5","4/5","2/5","1/5"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"A clock gains 5 minutes every hour. After 12 hours it shows:",options:["12:00","12:30","12:55","13:00"],correctIndex:3,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The mode of 2,3,4,4,5,5,5,6 is:",options:["3","4","5","6"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"If a² + b² = 25 and ab = 12, find (a+b)²:",options:["36","49","56","64"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"quantitative_aptitude",text:"The denominator of a fraction is 3 more than numerator. If 5 is added to both, fraction becomes 4/5. The fraction?",options:["7/10","11/14","3/6","9/12"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"quantitative_aptitude",text:"Circumference of circle with diameter 21 cm:",options:["33 cm","44 cm","55 cm","66 cm"],correctIndex:3,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"A boat goes 30 km downstream in 3 hrs and returns in 5 hrs. Speed in still water?",options:["5 km/h","7 km/h","8 km/h","10 km/h"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"quantitative_aptitude",text:"The value of 1 + 2 + 3 + ... + 50 =",options:["1225","1275","1325","1375"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"A person saves 20% of income. If expenses increase by 35%, savings become zero. Income:",options:["₹4000","₹5000","₹6000","Cannot determine"],correctIndex:3,difficulty:"HARD"},
{category:C,subject:"quantitative_aptitude",text:"The length of a rectangle is double its breadth. Perimeter is 36. Area?",options:["72","64","81","48"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"sin 30° + cos 60° equals:",options:["0","1","1/2","√3/2"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"Compound interest on ₹1000 at 10% for 3 years:",options:["₹300","₹310","₹331","₹350"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"quantitative_aptitude",text:"A ladder 10m long reaches a window 8m high. Distance of foot from wall?",options:["4m","5m","6m","7m"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"Three consecutive even numbers sum to 48. The largest:",options:["14","16","18","20"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"Surface area of sphere with radius 7 cm:",options:["516 cm²","616 cm²","716 cm²","816 cm²"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The value of 0.2 × 0.3 × 0.4 is:",options:["0.24","0.024","0.0024","2.4"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"If a triangle has sides 5,12,13 then it is:",options:["Equilateral","Isosceles","Right-angled","Scalene"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"The GCD of 18, 27 and 36 is:",options:["3","6","9","18"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"Speed of a car is 60 km/h. In meters per second it is:",options:["15 m/s","16.67 m/s","18 m/s","20 m/s"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"20 is what percent of 80?",options:["20%","25%","30%","35%"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"The number of diagonals in a pentagon is:",options:["3","4","5","6"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"quantitative_aptitude",text:"If 5 pens cost ₹35, the cost of 12 pens is:",options:["₹72","₹84","₹96","₹108"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"The remainder when 17 is divided by 5 is:",options:["0","1","2","3"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"quantitative_aptitude",text:"If a = 2, b = -3, the value of a³ + b³ is:",options:["-19","-35","35","19"],correctIndex:0,difficulty:"MEDIUM"},

// === REASONING (50) ===
{category:C,subject:"reasoning",text:"Find odd one out: Sparrow, Crow, Bat, Parrot",options:["Sparrow","Crow","Bat","Parrot"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Complete: 5, 11, 23, 47, ?",options:["93","94","95","96"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"MOUSE : PRXVH :: CHAIR : ?",options:["FKDLU","FKDLV","FKDMU","FLDLU"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"If P > Q, Q > R, R > S then which is the smallest?",options:["P","Q","R","S"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"A is father of B. B is brother of C. D is mother of C. How is A related to D?",options:["Brother","Father","Husband","Son"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Odd one out: Circle, Square, Triangle, Cylinder",options:["Circle","Square","Triangle","Cylinder"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Next in series: ACE, FHJ, KMO, ?",options:["PRT","PRU","QSU","PRS"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Pen : Write :: Knife : ?",options:["Injure","Peel","Cut","Stab"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"If GIVE=36, TAKE=27, then MAKE=?",options:["24","25","27","28"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"In a code RED = 345, BLUE = 6789. RUDE = ?",options:["3845","3945","3854","3954"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"P walks 10m south, turns left walks 5m, turns left walks 10m. Direction from start?",options:["South","East","North","West"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Which number replaces ?: 12, 15, 21, 30, ?",options:["36","40","42","45"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Calendar: What day was 15 Aug 1947?",options:["Monday","Tuesday","Friday","Wednesday"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Odd one out: Mercury, Venus, Moon, Mars",options:["Mercury","Venus","Moon","Mars"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Doctor : Hospital :: Teacher : ?",options:["Office","School","Factory","Court"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Find missing: 2, 6, 14, 30, ?",options:["60","62","54","58"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Statement: All pens are roads. Some roads are rivers. Conclusion: Some pens are rivers.",options:["Definitely true","Probably true","Definitely false","Cannot be determined"],correctIndex:3,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"In a row of 40 students, M is 11th from right. From left M is:",options:["28th","29th","30th","31st"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Odd one: January, February, June, March",options:["January","February","June","March"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Bird:Nest :: Dog:?",options:["Cave","Kennel","Stable","Burrow"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Choose the figure that completes the set: □○△ □○? ",options:["□","○","△","⬟"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"If BRIGHT is coded as ASHTFG, then LIGHT is?",options:["KHFGS","KHFSG","KGHFS","KHFGT"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Man:Biography :: Nation:?",options:["History","Democracy","Geography","Economy"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"A walks 3km East, turns right, walks 4km. Distance from start?",options:["3 km","4 km","5 km","7 km"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"How many pairs of letters in EXAMINATION have same number of letters between as in alphabet?",options:["3","4","5","6"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Arrange: (1) Word (2) Paragraph (3) Sentence (4) Letter (5) Chapter",options:["4,1,3,2,5","4,1,2,3,5","1,4,3,2,5","4,3,1,2,5"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Find wrong: 2, 5, 10, 17, 26, 37, 50, 65",options:["17","37","50","65"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Milk : Curd :: Grape : ?",options:["Juice","Jam","Wine","Jelly"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"If 5th March is Monday, what day is 5th April of same year?",options:["Wednesday","Thursday","Friday","Saturday"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"How many meaningful words can be formed from letters AETM?",options:["1","2","3","4"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Odd pair: AB-YZ, CD-WX, EF-UV, GH-TS",options:["AB-YZ","CD-WX","EF-UV","GH-TS"],correctIndex:3,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"A boy facing north turns 135° clockwise. Which direction he faces?",options:["South-East","South-West","North-East","North-West"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Eye : Myopia :: Teeth : ?",options:["Pyorrhoea","Cataract","Glaucoma","Diabetes"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"What comes next: B2C, D4F, H8J, ?",options:["N16P","P16R","L16N","P14R"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Odd: Guitar, Violin, Flute, Sitar",options:["Guitar","Violin","Flute","Sitar"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"If OLYMPICS = 152, CRICKET = ?",options:["86","88","90","92"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"In a family, A is brother of B, C is mother of A, D is father of C. B is ___ of D?",options:["Grandson","Granddaughter","Cannot determine","Son"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Number of faces, edges, vertices of cube: 6,12,?",options:["6","8","10","12"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Statement: Most dogs bark. Conclusion I: Some barking animals are dogs. II: Non-barking animals are not dogs.",options:["Only I follows","Only II follows","Both follow","Neither follows"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"If EARTH=15, SATURN=?",options:["18","20","22","24"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Marathon : Race :: Hibernate : ?",options:["Sleep","Winter","Bear","Dream"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"If 3*5=16, 4*7=23, then 5*9=?",options:["28","30","32","36"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Carpenter : Furniture :: Goldsmith : ?",options:["Gold","Ring","Ornament","Jewellery"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Pointing to a woman he said 'Her mother is the only daughter of my mother.' Who is the woman?",options:["Sister","Daughter","Mother","Niece"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Thermometer:Temperature :: Barometer:?",options:["Humidity","Wind","Pressure","Rainfall"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"If leaf=4, branch=6, tree=4. Forest=?",options:["4","5","6","7"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"reasoning",text:"Which is different: 32, 48, 64, 72, 96",options:["32","48","72","96"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"reasoning",text:"Clock:Time :: Thermometer:?",options:["Heat","Temperature","Mercury","Celsius"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"reasoning",text:"Complete: SCD, TEF, UGH, ?, WKL",options:["VIJ","VHI","VJK","UIJ"],correctIndex:0,difficulty:"MEDIUM"},

// === ENGLISH (50) ===
{category:C,subject:"english",text:"Choose the synonym of 'Abundant':",options:["Scarce","Plentiful","Little","Rare"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Antonym of 'Temporary':",options:["Brief","Permanent","Short","Passing"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Fill in: She ___ to school every day.",options:["go","goes","going","gone"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Passive voice: 'Tom writes a letter.'",options:["A letter is written by Tom","A letter was written by Tom","A letter written by Tom","A letter is wrote by Tom"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Meaning of idiom 'Kick the bucket':",options:["To kick something","To die","To run away","Fight"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Correctly spelt word:",options:["Independance","Independense","Independence","Indipendence"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"english",text:"One word: Speaking two languages fluently:",options:["Bilingual","Polyglot","Monolingual","Linguist"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Choose correct sentence:",options:["She sing well","She sings well","She singing well","She sung well"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Synonym of 'Naive':",options:["Clever","Innocent","Wise","Sharp"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Fill in: Ram is ___ honest man.",options:["a","an","the","no article"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Antonym of 'Conceal':",options:["Hide","Cover","Reveal","Bury"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"english",text:"Error: 'The furniture are very expensive.'",options:["The","furniture","are","expensive"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"'To let the cat out of the bag' means:",options:["Release a cat","Reveal a secret","Carry a bag","Feed a cat"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Indirect speech: She said, 'I have finished.'",options:["She said she has finished","She said she had finished","She said I had finished","She says she has finished"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Synonym of 'Endeavour':",options:["Rest","Attempt","Sleep","Stop"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Choose correct preposition: I am fond ___ music.",options:["in","at","of","for"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"english",text:"One word: One who eats human flesh:",options:["Herbivore","Cannibal","Carnivore","Omnivore"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Antonym of 'Rigid':",options:["Stiff","Flexible","Hard","Firm"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Fill in: He has been ill ___ Monday.",options:["from","for","since","at"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"english",text:"Meaning of 'At the drop of a hat':",options:["Losing a hat","Without hesitation","While wearing a hat","Very slowly"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Choose correct spelling:",options:["Conscientious","Conscientous","Consciencious","Conscentious"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"english",text:"Passive: 'They are building a new bridge.'",options:["A new bridge is being build","A new bridge is being built","A new bridge was being built","A new bridge has been built"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Synonym of 'Impeccable':",options:["Faulty","Flawless","Average","Normal"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"english",text:"Odd one out: Beautiful, Gorgeous, Ugly, Stunning",options:["Beautiful","Gorgeous","Ugly","Stunning"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"english",text:"'Achilles heel' means:",options:["Strong foot","A weakness","Fast runner","Brave soldier"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"english",text:"Error: 'One of the boy is absent.'",options:["One of","the","boy","is absent"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"english",text:"Fill in: The train arrived ___ time.",options:["in","at","on","by"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"One word: A person who looks at the bright side of things:",options:["Pessimist","Optimist","Realist","Idealist"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Synonym of 'Ponder':",options:["Rush","Think deeply","Run","Ignore"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Antonym of 'Frugal':",options:["Thrifty","Extravagant","Economical","Careful"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Cloze: The sun ___ in the east.",options:["rise","rises","rising","risen"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"'To beat around the bush' means:",options:["Garden work","Avoid the main topic","Hit bushes","Walk in forest"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Active voice: 'The work has been completed by them.'",options:["They complete the work","They completed the work","They have completed the work","They completing the work"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Select correct word: The ___ of the story is interesting.",options:["morale","moral","morals","morality"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Synonym of 'Lucid':",options:["Dark","Clear","Vague","Confused"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Antonym of 'Zenith':",options:["Peak","Summit","Nadir","Top"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"english",text:"Spelling: Which is correct?",options:["Liason","Liasion","Liaison","Liasson"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"english",text:"One word: A list of books available in a library:",options:["Catalogue","Bibliography","Index","Glossary"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Fill: She is allergic ___ dust.",options:["from","at","to","for"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Meaning of 'Blessing in disguise':",options:["Hidden curse","Good from apparent bad","Disguised person","Secret prayer"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Choose correct: 'The cattle ___ grazing.'",options:["is","was","are","has been"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Synonym of 'Audacious':",options:["Timid","Bold","Quiet","Shy"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Antonym of 'Verbose':",options:["Wordy","Concise","Lengthy","Detailed"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"english",text:"Error: 'He gave me a good advise.'",options:["He","gave","a good","advise"],correctIndex:3,difficulty:"MEDIUM"},
{category:C,subject:"english",text:"Meaning of 'Under the weather':",options:["In rain","Feeling ill","Cold outside","Sunny day"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"One word: Study of birds:",options:["Zoology","Ornithology","Botany","Entomology"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"english",text:"Fill: I look forward ___ hearing from you.",options:["at","for","in","to"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"english",text:"Synonym of 'Ephemeral':",options:["Lasting","Short-lived","Permanent","Eternal"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"english",text:"'Piece of cake' means:",options:["A bakery item","Something very easy","A reward","Desert"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"english",text:"Correctly spelt:",options:["Necesary","Neccessary","Necessary","Necessery"],correctIndex:2,difficulty:"EASY"},

// === GENERAL AWARENESS (50) ===
{category:C,subject:"general_awareness",text:"Who wrote the Indian National Anthem?",options:["Bankim Chandra","Rabindranath Tagore","Mahatma Gandhi","Jawaharlal Nehru"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"The capital of Australia is:",options:["Sydney","Melbourne","Canberra","Perth"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Who was the first President of India?",options:["Jawaharlal Nehru","Dr. Rajendra Prasad","Sardar Patel","B.R. Ambedkar"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Which planet is known as the Red Planet?",options:["Jupiter","Venus","Mars","Saturn"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"The Quit India Movement was launched in:",options:["1940","1942","1944","1946"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The longest river in India is:",options:["Yamuna","Godavari","Ganga","Brahmaputra"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Who is known as the 'Missile Man of India'?",options:["Vikram Sarabhai","APJ Abdul Kalam","Homi Bhabha","C.V. Raman"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Which vitamin is obtained from sunlight?",options:["Vitamin A","Vitamin B","Vitamin C","Vitamin D"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"The Battle of Plassey was fought in:",options:["1757","1764","1857","1947"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The chemical formula of water is:",options:["H2O2","HO2","H2O","OH"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Which gas do plants absorb from the atmosphere?",options:["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"The Panchayati Raj system was introduced in India in:",options:["1947","1950","1959","1965"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Which state has the longest coastline in India?",options:["Kerala","Tamil Nadu","Gujarat","Maharashtra"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The SI unit of force is:",options:["Joule","Watt","Newton","Pascal"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Who founded the Arya Samaj?",options:["Raja Ram Mohan Roy","Swami Vivekananda","Swami Dayanand Saraswati","Mahatma Gandhi"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Which Article of the Constitution deals with Right to Equality?",options:["Article 14","Article 19","Article 21","Article 32"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The smallest bone in the human body is:",options:["Femur","Tibia","Stirrup (Stapes)","Radius"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Bhakra Nangal Dam is built on which river?",options:["Ganga","Sutlej","Yamuna","Godavari"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The 'Trail of Tears' refers to the forced relocation of which group?",options:["African Americans","Native Americans","Australian Aboriginals","Rohingya"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"general_awareness",text:"Which metal is the best conductor of electricity?",options:["Iron","Copper","Silver","Gold"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The Lokpal Bill was passed in which year?",options:["2011","2013","2015","2017"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Which is the largest desert in the world?",options:["Sahara","Gobi","Thar","Antarctic"],correctIndex:3,difficulty:"HARD"},
{category:C,subject:"general_awareness",text:"The pH value of pure water is:",options:["5","6","7","8"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Aurangzeb was the son of:",options:["Akbar","Jahangir","Shah Jahan","Babur"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The first Five Year Plan started in:",options:["1947","1950","1951","1955"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The Tropic of Cancer passes through how many Indian states?",options:["6","7","8","9"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"general_awareness",text:"Which organ in the human body produces insulin?",options:["Liver","Kidney","Pancreas","Heart"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The headquarters of WHO is in:",options:["New York","Geneva","London","Paris"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"The Mughal Empire was founded by:",options:["Akbar","Humayun","Babur","Shah Jahan"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"The National Anthem of India was first sung in:",options:["1905","1906","1911","1947"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"An atom is made up of:",options:["Protons only","Protons and Neutrons","Protons, Neutrons and Electrons","Electrons only"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Who is known as the Iron Man of India?",options:["Subhash Chandra Bose","Bhagat Singh","Sardar Vallabhbhai Patel","Jawaharlal Nehru"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"The Green Revolution was led by:",options:["Verghese Kurien","M.S. Swaminathan","Norman Borlaug","Amartya Sen"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Which schedule of the Indian Constitution lists the languages?",options:["6th","7th","8th","9th"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"general_awareness",text:"The ozone layer is found in which part of the atmosphere?",options:["Troposphere","Stratosphere","Mesosphere","Thermosphere"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Photosynthesis produces:",options:["Carbon dioxide","Oxygen","Nitrogen","Hydrogen"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Who gave the slogan 'Do or Die'?",options:["Subhash Chandra Bose","Bal Gangadhar Tilak","Mahatma Gandhi","Jawaharlal Nehru"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"The total number of Fundamental Rights in Indian Constitution:",options:["5","6","7","8"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Diamond is an allotrope of:",options:["Silicon","Sulphur","Carbon","Phosphorus"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The Jallianwala Bagh massacre took place in:",options:["1917","1919","1921","1930"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"Which planet is the largest in our solar system?",options:["Saturn","Mars","Jupiter","Neptune"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"The Simon Commission visited India in:",options:["1925","1928","1930","1932"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Malaria is caused by:",options:["Virus","Bacteria","Protozoa","Fungus"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The Directive Principles are in which Part of the Constitution?",options:["Part III","Part IV","Part V","Part VI"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Which river is called the 'Sorrow of Bengal'?",options:["Ganga","Hooghly","Damodar","Brahmaputra"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"The Universal Declaration of Human Rights was adopted in:",options:["1945","1948","1950","1955"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Blood group discovered by:",options:["William Harvey","Karl Landsteiner","Louis Pasteur","Alexander Fleming"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"general_awareness",text:"The longest highway in India is:",options:["NH 44","NH 27","NH 48","NH 7"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"general_awareness",text:"Who is known as the father of Indian Constitution?",options:["Mahatma Gandhi","Jawaharlal Nehru","B.R. Ambedkar","Sardar Patel"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"general_awareness",text:"The speed of sound in air at 20°C is approximately:",options:["250 m/s","300 m/s","343 m/s","400 m/s"],correctIndex:2,difficulty:"MEDIUM"},
];
