interface Q { category: string; subject: string; text: string; options: string[]; correctIndex: number; explanation?: string; difficulty?: string; }
const C = "UPSC";
export const upscQuestions: Q[] = [
// === POLITY (50) ===
{category:C,subject:"polity",text:"The Indian Constitution came into effect on:",options:["26 Jan 1947","15 Aug 1947","26 Jan 1950","26 Nov 1949"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"polity",text:"How many articles are there in the Indian Constitution originally?",options:["350","395","448","300"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"The Preamble of Indian Constitution has been amended:",options:["Once","Twice","Thrice","Never"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"The concept of Fundamental Rights is borrowed from:",options:["UK","USA","Ireland","France"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"Article 21 deals with:",options:["Right to Equality","Right to Freedom of Speech","Right to Life and Liberty","Right to Education"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"polity",text:"The President of India is elected by:",options:["People directly","Parliament","Electoral College","Lok Sabha only"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"Money Bill can be introduced in:",options:["Rajya Sabha","Lok Sabha","Both Houses","Either House"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"polity",text:"The Rajya Sabha members are elected for:",options:["4 years","5 years","6 years","Life"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"polity",text:"Judicial Review in India is from which country?",options:["USA","UK","Canada","France"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"The 73rd Amendment deals with:",options:["Municipalities","Panchayati Raj","Anti-defection","Fundamental Duties"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"CAG reports to:",options:["Prime Minister","President","Parliament","Chief Justice"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"Emergency under Article 352 is called:",options:["State Emergency","Financial Emergency","National Emergency","Constitutional Emergency"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"polity",text:"Who appoints the Chief Justice of India?",options:["Prime Minister","Parliament","President","Law Minister"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"polity",text:"Directive Principles are inspired by:",options:["US Constitution","Irish Constitution","Canadian Constitution","UK Constitution"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"The minimum age to become PM of India is:",options:["21","25","30","35"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"polity",text:"Part IV-A of Constitution deals with:",options:["Fundamental Rights","DPSP","Fundamental Duties","Citizenship"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"The concept of Single Citizenship in India is borrowed from:",options:["USA","UK","Canada","France"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"polity",text:"Anti-defection law is in which schedule?",options:["8th","9th","10th","11th"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"Article 370 was related to:",options:["Punjab","Assam","Jammu & Kashmir","Nagaland"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"polity",text:"The Speaker of Lok Sabha is removed by:",options:["President","Prime Minister","Resolution of Lok Sabha","Chief Justice"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"Which writ means 'to have the body'?",options:["Mandamus","Certiorari","Habeas Corpus","Quo Warranto"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"polity",text:"Inter-State Council is established under:",options:["Article 256","Article 263","Article 280","Article 300"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"polity",text:"The Finance Commission is constituted every:",options:["3 years","4 years","5 years","6 years"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"RTI Act was passed in:",options:["2003","2004","2005","2006"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"polity",text:"Residuary powers in India lie with:",options:["State","Centre","Both","Panchayat"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"The total strength of Lok Sabha is:",options:["530","543","545","552"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"polity",text:"Who is the guardian of Fundamental Rights?",options:["President","Parliament","Supreme Court","Prime Minister"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"polity",text:"Article 32 is related to:",options:["Right to Education","Constitutional Remedies","Right to Property","Freedom of Religion"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"The concept of Emergency is borrowed from:",options:["Germany","France","USA","UK"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"polity",text:"Who presides over joint sitting of Parliament?",options:["President","Vice President","Speaker of Lok Sabha","PM"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"Maximum strength of Rajya Sabha is:",options:["238","245","250","260"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"polity",text:"Which part of Constitution deals with Union Territories?",options:["Part VI","Part VII","Part VIII","Part IX"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"polity",text:"Fundamental Duties were added by which amendment?",options:["42nd","44th","46th","52nd"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"The Attorney General is appointed by:",options:["Chief Justice","Prime Minister","President","Law Minister"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"Zero Hour is a feature of:",options:["Indian Parliament","British Parliament","US Congress","French Assembly"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"National Human Rights Commission chairman must be:",options:["A lawyer","Retired CJI","A politician","A bureaucrat"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"polity",text:"Which list is not in the Constitution?",options:["Union List","State List","Concurrent List","Municipal List"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"polity",text:"The concept of DPSP is from which country's constitution?",options:["USA","UK","Ireland","Australia"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"Who can dissolve Lok Sabha?",options:["Speaker","Prime Minister","President","Vice President"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"polity",text:"Article 17 abolishes:",options:["Bonded Labour","Child Labour","Untouchability","Slavery"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"Election Commission is established under which Article?",options:["Article 280","Article 300","Article 324","Article 350"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"The first General Elections in India were held in:",options:["1950","1951-52","1955","1957"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"Protem Speaker is appointed by:",options:["Chief Justice","President","Prime Minister","Outgoing Speaker"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"polity",text:"Which schedule contains languages?",options:["7th","8th","9th","10th"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"polity",text:"No-confidence motion can be moved in:",options:["Rajya Sabha","Lok Sabha","Both Houses","State Assembly only"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"polity",text:"The Constitutional Amendment to lower voting age to 18 was:",options:["42nd","44th","61st","73rd"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"polity",text:"President's Rule is under which Article?",options:["Article 352","Article 356","Article 360","Article 365"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"polity",text:"How many schedules in the Indian Constitution?",options:["8","10","12","14"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"polity",text:"The Constitutional Assembly's last session was chaired by:",options:["Jawaharlal Nehru","Dr. Rajendra Prasad","Dr. B.R. Ambedkar","Sardar Patel"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"polity",text:"Secularism was added to Preamble by which amendment?",options:["1st","25th","42nd","44th"],correctIndex:2,difficulty:"MEDIUM"},

// === HISTORY (50) ===
{category:C,subject:"history",text:"The Indus Valley Civilization flourished around:",options:["3000 BC","2500 BC","1500 BC","500 BC"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"history",text:"Who was the founder of the Maurya dynasty?",options:["Ashoka","Bindusara","Chandragupta Maurya","Chanakya"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"history",text:"The Battle of Panipat (1526) was fought between:",options:["Babur and Ibrahim Lodi","Akbar and Hemu","Humayun and Sher Shah","Aurangzeb and Dara Shikoh"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"Who built the Qutub Minar?",options:["Qutub-ud-din Aibak","Iltutmish","Balban","Razia Sultan"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Dandi March took place in:",options:["1928","1930","1932","1934"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"history",text:"The first ruler of the Slave Dynasty was:",options:["Iltutmish","Balban","Qutub-ud-din Aibak","Razia Sultan"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"Ashoka fought the Kalinga War in:",options:["265 BC","261 BC","256 BC","250 BC"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"Who started the Bhakti Movement in the South?",options:["Kabir","Ramanuja","Nanak","Chaitanya"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"history",text:"The Sepoy Mutiny of 1857 started from:",options:["Delhi","Lucknow","Meerut","Kanpur"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"history",text:"Akbar's revenue system was called:",options:["Iqta","Mansabdari","Todarmal's Dahsala","Jagirdari"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The INC was founded in:",options:["1880","1885","1890","1895"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"history",text:"Who was the Viceroy during the Partition of Bengal (1905)?",options:["Lord Curzon","Lord Minto","Lord Ripon","Lord Dalhousie"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Non-Cooperation Movement was launched in:",options:["1919","1920","1921","1922"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Harappan civilization was discovered in:",options:["1915","1920","1921","1925"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"Who wrote 'Arthashastra'?",options:["Ashoka","Chanakya","Megasthenes","Fa-hien"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"history",text:"The Gupta period is known as the:",options:["Iron Age","Silver Age","Golden Age","Bronze Age"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"history",text:"The Rowlatt Act was passed in:",options:["1917","1918","1919","1920"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"Jallianwala Bagh massacre was ordered by:",options:["General Dyer","Lord Chelmsford","Lord Irwin","Lord Curzon"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"history",text:"The Cabinet Mission came to India in:",options:["1942","1944","1946","1947"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"Who gave the slogan 'Jai Hind'?",options:["Mahatma Gandhi","Jawaharlal Nehru","Subhash Chandra Bose","Bhagat Singh"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"history",text:"The Doctrine of Lapse was introduced by:",options:["Lord Wellesley","Lord Dalhousie","Lord Canning","Lord Cornwallis"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Vedas are written in:",options:["Pali","Prakrit","Sanskrit","Tamil"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"history",text:"Who is called the 'Napoleon of India'?",options:["Ashoka","Chandragupta I","Samudragupta","Akbar"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Simon Commission visited India in:",options:["1925","1927","1928","1930"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Indian National Army was founded by:",options:["Subhash Chandra Bose","Rashbehari Bose","Mohan Singh","All of these"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"history",text:"Who was the last Mughal emperor?",options:["Aurangzeb","Shah Alam II","Bahadur Shah Zafar","Muhammad Shah"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Champaran Satyagraha was in:",options:["1915","1917","1919","1920"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"Rig Veda is primarily about:",options:["Rituals","Hymns to Gods","Medicine","Philosophy"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Treaty of Srirangapatnam was signed in:",options:["1784","1792","1799","1801"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"history",text:"Who was the first woman ruler of Delhi Sultanate?",options:["Nur Jahan","Razia Sultan","Chand Bibi","Mumtaz"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"history",text:"The Permanent Settlement was introduced by:",options:["Lord Cornwallis","Lord Wellesley","Lord Hastings","Lord Clive"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"Second Round Table Conference was attended by:",options:["Jawaharlal Nehru","Mahatma Gandhi","Subhash Chandra Bose","None of them"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Swadeshi Movement was against:",options:["Rowlatt Act","Partition of Bengal","Salt Tax","Simon Commission"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"Ajanta Caves are famous for:",options:["Rock-cut temples","Paintings","Sculptures","All of these"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"history",text:"Who introduced the Subsidiary Alliance?",options:["Lord Wellesley","Lord Dalhousie","Lord Cornwallis","Lord Clive"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Poona Pact was between:",options:["Gandhi and Jinnah","Gandhi and Ambedkar","Nehru and Patel","Tilak and Gokhale"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Cripps Mission came to India in:",options:["1940","1942","1944","1946"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"Buddhist literature is written in:",options:["Sanskrit","Tamil","Pali","Hindi"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"Who built the city of Fatehpur Sikri?",options:["Shah Jahan","Babur","Akbar","Humayun"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Home Rule Movement was started by:",options:["Tilak and Annie Besant","Gandhi and Nehru","Bose and Patel","Gokhale and Naoroji"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Chinese traveler who visited India during Gupta period:",options:["Hiuen Tsang","Fa-hien","I-tsing","Megasthenes"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The first session of INC was held at:",options:["Calcutta","Bombay","Madras","Allahabad"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"Who introduced the system of provincial autonomy in India?",options:["Indian Councils Act 1909","Government of India Act 1919","Government of India Act 1935","Indian Independence Act"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"history",text:"The Khilafat Movement was related to:",options:["Hindu-Muslim unity","Protection of Caliph","Against British taxation","For Indian independence"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Battle of Haldighati was fought in:",options:["1576","1556","1600","1526"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"Who was the first Governor General of free India?",options:["Lord Mountbatten","C. Rajagopalachari","Dr. Rajendra Prasad","Jawaharlal Nehru"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Lucknow Pact (1916) was between:",options:["INC and Muslim League","INC and British","British and Muslim League","INC and Hindu Mahasabha"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"history",text:"The Ilbert Bill controversy was during which Viceroy?",options:["Lord Ripon","Lord Curzon","Lord Lytton","Lord Mayo"],correctIndex:0,difficulty:"HARD"},
{category:C,subject:"history",text:"Ancient Indian university Nalanda is in which state?",options:["UP","MP","Bihar","Rajasthan"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"history",text:"Who translated the Quran into Persian?",options:["Dara Shikoh","Akbar","Aurangzeb","Shah Jahan"],correctIndex:0,difficulty:"HARD"},

// === GEOGRAPHY (50) ===
{category:C,subject:"geography",text:"The largest continent by area is:",options:["Africa","North America","Asia","Europe"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"geography",text:"The Tropic of Cancer passes through India at:",options:["23.5° N","23.5° S","0°","66.5° N"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"geography",text:"Which Indian state has the largest area?",options:["Madhya Pradesh","Maharashtra","Rajasthan","Uttar Pradesh"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"geography",text:"The Deccan Plateau is part of:",options:["Northern India","Peninsular India","Eastern India","Western India"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"geography",text:"Which soil is best for cotton cultivation?",options:["Alluvial","Black (Regur)","Laterite","Red"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"The Western Ghats are also known as:",options:["Sahyadri","Vindhya","Aravalli","Satpura"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"India's standard meridian is:",options:["82°30' E","80° E","85° E","90° E"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Which river forms the India-Bangladesh border?",options:["Ganga","Brahmaputra","Meghna","Teesta"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"geography",text:"The highest peak in India is:",options:["Kanchenjunga","K2","Nanda Devi","Mt. Everest"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Monsoons in India are caused by:",options:["Trade winds","Westerlies","Differential heating of land and sea","Jet streams only"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"The largest lake in India is:",options:["Wular Lake","Dal Lake","Chilika Lake","Pulicat Lake"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Tides are caused by:",options:["Wind","Earthquakes","Gravitational pull of Moon and Sun","Earth's rotation only"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Which ocean is the largest?",options:["Atlantic","Indian","Arctic","Pacific"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"geography",text:"The Ring of Fire is associated with:",options:["Volcanoes","Forests","Deserts","Glaciers"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"geography",text:"The Equator passes through how many continents?",options:["2","3","4","5"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Which type of rainfall is common in equatorial regions?",options:["Orographic","Convectional","Cyclonic","Frontal"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Laterite soil is found mainly in:",options:["Northern Plains","Thar Desert","Areas with heavy rainfall","Cold regions"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"The Palk Strait separates India from:",options:["Bangladesh","Myanmar","Sri Lanka","Pakistan"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"geography",text:"The longest river in the world is:",options:["Amazon","Nile","Mississippi","Yangtze"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"geography",text:"Which Indian state receives the highest rainfall?",options:["Kerala","Assam","Meghalaya","Karnataka"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"geography",text:"The Sundarbans is located in:",options:["Odisha","West Bengal","Assam","Kerala"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"geography",text:"Earthquake waves are recorded by:",options:["Barometer","Seismograph","Anemometer","Thermometer"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"geography",text:"The Aravalli Range is in:",options:["MP","Karnataka","Rajasthan","Gujarat"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"geography",text:"Which crop is known as 'Golden Fibre'?",options:["Cotton","Silk","Jute","Hemp"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"The deepest ocean trench is:",options:["Tonga Trench","Mariana Trench","Java Trench","Puerto Rico Trench"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"geography",text:"Coral reefs are formed by:",options:["Volcanic action","Marine organisms","River deposits","Wind erosion"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Which wind brings winter rainfall to Tamil Nadu?",options:["South-West Monsoon","North-East Monsoon","Trade Winds","Westerlies"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"The major iron ore producing state in India:",options:["Jharkhand","Odisha","Goa","Karnataka"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Mangrove forests are found at:",options:["Coastal areas","Mountain peaks","Desert regions","Plains"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"geography",text:"The Siachen Glacier is located in:",options:["Himachal Pradesh","Uttarakhand","Karakoram Range","Sikkim"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Which latitude divides Earth into Northern and Southern hemispheres?",options:["Tropic of Cancer","Tropic of Capricorn","Equator","Prime Meridian"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"geography",text:"Kaziranga National Park is famous for:",options:["Tigers","Lions","One-horned Rhinos","Elephants"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"geography",text:"The largest delta in the world is:",options:["Nile Delta","Mekong Delta","Ganges-Brahmaputra Delta","Mississippi Delta"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Ozone depletion is caused mainly by:",options:["CO2","CFCs","Methane","Nitrogen"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Which country has the largest population?",options:["India","USA","China","Indonesia"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"geography",text:"The time difference between IST and GMT is:",options:["4 hours","4.5 hours","5 hours","5.5 hours"],correctIndex:3,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Which is the longest national highway in India?",options:["NH 44","NH 27","NH 48","NH 2"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"The Narmada River flows into:",options:["Bay of Bengal","Arabian Sea","Indian Ocean","Both Bay and Arabian"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Jim Corbett National Park is in:",options:["MP","Rajasthan","Uttarakhand","Assam"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"geography",text:"Continental drift theory was proposed by:",options:["Wegener","Darwin","Newton","Hutton"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"The Thar Desert is in which Indian state?",options:["Gujarat","Rajasthan","Haryana","Punjab"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"geography",text:"Which layer of atmosphere is closest to Earth?",options:["Stratosphere","Mesosphere","Troposphere","Thermosphere"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"geography",text:"Tea is mainly grown in:",options:["Rajasthan","Assam","Gujarat","MP"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"geography",text:"The highest waterfall in India is:",options:["Jog Falls","Dudhsagar Falls","Kunchikal Falls","Athirappilly Falls"],correctIndex:2,difficulty:"HARD"},
{category:C,subject:"geography",text:"Which Indian state shares border with maximum states?",options:["MP","UP","Assam","Rajasthan"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"geography",text:"Tsunamis are caused by:",options:["Wind","Tides","Underwater earthquakes","Rainfall"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"geography",text:"The Black Forest is in:",options:["France","Germany","Switzerland","Austria"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Which planet is closest to the Sun?",options:["Venus","Earth","Mercury","Mars"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"geography",text:"The major coffee producing state in India is:",options:["Tamil Nadu","Kerala","Karnataka","Assam"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"geography",text:"Earth's crust is made up of moving plates. This is explained by:",options:["Continental Drift","Plate Tectonics","Sea Floor Spreading","Isostasy"],correctIndex:1,difficulty:"MEDIUM"},

// === ECONOMICS (50) ===
{category:C,subject:"economics",text:"GDP measures:",options:["National happiness","Total production of goods and services","Government spending only","Trade balance"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"economics",text:"The current Five Year Plans are replaced by:",options:["Ten Year Plans","Annual Plans","NITI Aayog Initiatives","Three Year Plans"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"The fiscal deficit is:",options:["Total revenue - Total expenditure","Total borrowing","Excess of govt expenditure over receipts excluding borrowing","Budget surplus"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"Inflation means:",options:["Fall in prices","Rise in general price level","Stable prices","Deflation"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"economics",text:"WPI measures inflation at:",options:["Retail level","Wholesale level","Farm level","International level"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"economics",text:"Which sector contributes most to India's GDP?",options:["Agriculture","Industry","Services","Mining"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"The poverty line in India is determined by:",options:["World Bank","RBI","NITI Aayog","Planning Commission (earlier)"],correctIndex:3,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"Mixed economy means:",options:["Only public sector","Only private sector","Both public and private sectors","No government role"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"economics",text:"LPG reforms in India refer to:",options:["Cooking gas policy","Liberalization, Privatization, Globalization","Land Policy Guidelines","Local Production Growth"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"economics",text:"The 1991 economic reforms were introduced by:",options:["Rajiv Gandhi","VP Singh","PV Narasimha Rao","Atal Bihari Vajpayee"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"CPI measures:",options:["Industrial output","Consumer price changes","Capital investment","Corporate profits"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"economics",text:"Direct tax includes:",options:["GST","Income Tax","Excise Duty","Custom Duty"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"economics",text:"Demand Pull inflation is caused by:",options:["Decrease in supply","Increase in demand","Government policy","Foreign exchange"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"The largest employer in India is:",options:["IT sector","Agriculture","Manufacturing","Services"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"economics",text:"Green GDP accounts for:",options:["Only agriculture","Environmental damage from growth","Green energy","Forest cover"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"economics",text:"The Union Budget is presented in which month?",options:["January","February","March","April"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"economics",text:"HDI is measured by:",options:["World Bank","UNDP","IMF","WTO"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"Disguised unemployment is mainly found in:",options:["Industry","Services","Agriculture","IT"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"Which organization collects Census data in India?",options:["NSSO","Registrar General","CSO","NITI Aayog"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"Open market operations are conducted by:",options:["Finance Ministry","SEBI","RBI","Stock Exchange"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"MGNREGA is related to:",options:["Education","Health","Employment","Housing"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"economics",text:"The base year for current GDP calculation is:",options:["2004-05","2011-12","2015-16","2019-20"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"Per capita income means:",options:["Total income","Average income per person","Government revenue","Corporate profit"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"economics",text:"Which plan targeted 'Garibi Hatao'?",options:["3rd Plan","4th Plan","5th Plan","6th Plan"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"FDI stands for:",options:["Foreign Direct Investment","Financial Domestic Investment","Federal Direct Import","None"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"economics",text:"India's largest trading partner is:",options:["USA","China","Japan","UK"],correctIndex:0,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"The GST Council is headed by:",options:["RBI Governor","Finance Minister","PM","Commerce Minister"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"Disinvestment means:",options:["New investment","Selling government stake in PSUs","Foreign investment","Bank deposits"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"The concept of 'Demographic Dividend' refers to:",options:["Aging population","Large working-age population","High birth rate","Low death rate"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"Which is NOT a component of HDI?",options:["Life expectancy","Education","Standard of living","Military spending"],correctIndex:3,difficulty:"EASY"},
{category:C,subject:"economics",text:"SEZ stands for:",options:["Special Economic Zone","Standard Export Zone","Strategic Economic Zone","None"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"economics",text:"What is BOP?",options:["Balance of Plan","Balance of Payments","Bank of Production","Budget of Payments"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"The Indian Rupee is:",options:["Fully convertible","Partially convertible on current account","Not convertible","Fully convertible on capital account"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"economics",text:"NABARD is related to:",options:["Urban banking","Rural development","Foreign trade","Stock market"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"economics",text:"PPP stands for:",options:["Public Private Partnership","Purchasing Power Parity","Both depending on context","None"],correctIndex:2,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"Gini coefficient measures:",options:["GDP growth","Income inequality","Inflation","Poverty"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"economics",text:"Which tax replaced multiple indirect taxes in India?",options:["VAT","Service Tax","GST","Excise"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"economics",text:"National income at factor cost means:",options:["GDP + subsidies","NNP at factor cost","GDP at market price","GNP + taxes"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"economics",text:"Make in India was launched in:",options:["2012","2014","2016","2018"],correctIndex:1,difficulty:"EASY"},
{category:C,subject:"economics",text:"RBI's monetary policy primarily controls:",options:["Fiscal deficit","Money supply and interest rates","Government spending","Trade policy"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"Which committee was related to tax reforms?",options:["Kelkar Committee","Wanchoo Committee","Raghuram Rajan Committee","All of these"],correctIndex:3,difficulty:"HARD"},
{category:C,subject:"economics",text:"Census in India is conducted every:",options:["5 years","7 years","10 years","15 years"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"economics",text:"Stagflation is:",options:["High growth + low inflation","Low growth + high inflation","High growth + high inflation","Low growth + low inflation"],correctIndex:1,difficulty:"HARD"},
{category:C,subject:"economics",text:"Rural poverty has declined mainly due to:",options:["Urbanization","Green Revolution","IT boom","Exports"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"External debt of India is managed by:",options:["RBI","Finance Ministry","SEBI","Both RBI and Finance Ministry"],correctIndex:3,difficulty:"HARD"},
{category:C,subject:"economics",text:"The primary sector includes:",options:["Manufacturing","IT","Agriculture and mining","Banking"],correctIndex:2,difficulty:"EASY"},
{category:C,subject:"economics",text:"India adopted economic planning from:",options:["USA","USSR","UK","China"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"Demonetization in India was announced on:",options:["Nov 8, 2016","Nov 8, 2017","Oct 8, 2016","Dec 8, 2016"],correctIndex:0,difficulty:"EASY"},
{category:C,subject:"economics",text:"What is the sex ratio measured as in India?",options:["Males per 1000 females","Females per 1000 males","Equal ratio","Males per 100"],correctIndex:1,difficulty:"MEDIUM"},
{category:C,subject:"economics",text:"Food Security Act was passed in:",options:["2011","2012","2013","2014"],correctIndex:2,difficulty:"MEDIUM"},
];
